### ISSUE TITLE
Failover of IP seems to cause problems in the bus events connection pool

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill-commons#10]
We noticed during failover testing that if the IP of the database changes, failover takes much longer than it does when it remains the same.

Amazon RDS does failover based on DNS with a very short TTL.  We can configured the JVM to prevent DNS caching, and set "org.killbill.dao.connectionTimeout" and "org.killbill.dao.idleConnectionTestPeriod" to 1s.  We tried experimenting with various connection pool settings as well.

After a failover it takes about 5 minutes before we stop seeing errors and requests go through again.  They appear to come from bus event threads that continue to trickle in for a few minutes:

2015-02-06 16:13:21,563 [bus_ext_events-th] WARN  o.k.queue.DefaultQueueLifecycle - Bus: Thread  bus_ext_events-th  [39] got an exception, catching and moving on...
org.skife.jdbi.v2.exceptions.UnableToObtainConnectionException: java.sql.SQLException: Timeout of 10000ms encountered waiting for connection.

We tried using haproxy to proxy the database connections and provide a static IP to kill bill.  When we do this, we can get failover to happen in just a few seconds.

A fix is not a priority for us since deploying haproxy solves the issue entirely, but we were just wondering if there were settings we were missing to make it work without it.

**Comment by pierre** [comment]
See https://github.com/killbill/killbill/issues/709.
