### ISSUE TITLE
Reaper over-reporting late entries

### ISSUE THREAD

**Issue by pierre** [killbill/killbill-commons#162]
We shouldn't call `addAll` in the `for` loop:

https://github.com/killbill/killbill-commons/blob/a152b9f53962cbde154a0ac0fb368e8a0a9a2574/queue/src/main/java/org/killbill/queue/DBBackedQueue.java#L298

**Comment by kuguobing** [comment]
for version 0.24.21 (0.24.*), need to fix also @xsalefter @pierre

**Comment by xsalefter** [comment]
Hi @kuguobing unfortunately, we won't backport this into `0.24.x`. My only suggestion is that you update Kill Kill version to latest version. Or, if you just use `killbill-commons` version and not Kill Bill, you should able to update `killbill-commons` into latest version as well.

**Comment by xsalefter** [comment]
As this issue fixed in main branch, I'll close this issue.
