### ISSUE TITLE
Queue stuck entries with single node system

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill-commons#169]
In situations where some notification entries are left `IN_PROCESSING` state, we typically have a reaper mechanism to re-dispatch such entries. However in a single node scenario, we cannot re-dispatch to another node and currently the code just prints a [warning](https://github.com/killbill/killbill-commons/blob/killbill-commons-0.26.2/queue/src/main/java/org/killbill/queue/DBBackedQueue.java#L296). Note that such situations could arise as a result of a shutdown that timed out or a node that was killed abruptly.

Such entries will not be picked up since the query for ready entries only looks at `AVAILABLE` state.

**Comment by sbrossie** [comment]
One proposal would be to have the reaper reset the state to `AVAILABLE` - in multi-node scenario this is what it does when it re-dispatches to another node. The worts case scenario is that such notification gets dispatched twice - which is an expected edge use case anyways.

**Comment by sbrossie** [comment]
Actually, one issue is if system gets really late: It would make no sense to re-dispatch (reap) entries on the same node, so the question is how can we differentiate between the 2 use cases:
1. A few entries were left hanging in `IN_PROCESSING ` state and would need to be reaped
2. System is late and we have potentially a few (or many entries) late

The [reaper query](https://github.com/killbill/killbill-commons/blob/killbill-commons-0.26.2/queue/src/main/resources/org/killbill/notificationq/dao/NotificationSqlDao.sql.stg#L22) would pick up entries where `processing_state`=`IN_PROCESSING` (case 1) but would also pick entries where `processing_state` is null (case 2), so we have no way to discriminate unless we change the query.

Proposal: When we detect an `entryIsBeingProcessedByThisNode` we could check that status is `IN_PROCESSING` and only re-dispatch (reap) those entries.

**Comment by rk-git** [comment]
I have build up the illmill war from the branch containing this fix.
Could you please let me know what tests you ran to confirm the fix?
I need to do the same.
