### ISSUE TITLE
Bus and notification queue uniformization

### ISSUE THREAD

**Issue by pierre** [killbill/killbill-commons#21]
The code between the two is very similar these days: can we unify the libraries further?

Additionally, could retries be built-in? We have several implementations:

* Built-in (simple version, retry right away then give up)
* Custom:
  * JAX-RS push notifications,
  * Payment
  * Retries for entitlement, subscription, invoice and overdue bus and notifications queues (for plugins)

**Comment by sbrossie** [comment]
I believe all this has been built:
* We have the ability to set retries (right away) through `org.killbill.notificationq.${instanceName}.max.failure.retry` property
* We also support re-queuing using the `RetryableInternalException` mechanism

@pierre Can this be closed?
