### ISSUE TITLE
TestDOTBuilder is failing

### ISSUE THREAD

**Issue by kevinpostlewaite** [killbill/killbill-commons#4]
From Pierre:
" it's a bug indeed in the test. The ordering of key/value pairs is not deterministic, i.e. node_16 [color=grey style=filled label=INIT]; becomes node_16 [style=filled color=grey label=INIT]; on your machine. Funny we never ran into it, maybe you have a different Java version?"

Java version: Java(TM) SE Runtime Environment (build 1.8.0_05-b13)

GM16799:surefire-reports kpostlewaite$ cat testng-results.xml 
<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Command line suite" duration-ms="295" started-at="2014-06-25T00:53:18Z" finished-at="2014-06-25T00:53:18Z">
    <groups>
      <group name="fast">
        <method signature="TestDOTBuilder.testGenerator()[pri:0, instance:org.killbill.automaton.dot.TestDOTBuilder@6615435c]" name="testGenerator" class="org.killbill.automaton.dot.TestDOTBuilder"/>
        <method signature="TestStateMachine.testLinkedStateMachines()[pri:0, instance:org.killbill.automaton.TestStateMachine@5315b42e]" name="testLinkedStateMachines" class="org.killbill.automaton.TestStateMachine"/>
        <method signature="TestStateMachine.testStateMachine()[pri:0, instance:org.killbill.automaton.TestStateMachine@5315b42e]" name="testStateMachine" class="org.killbill.automaton.TestStateMachine"/>
        <method signature="TestStateMachine.testStateTransition()[pri:0, instance:org.killbill.automaton.TestStateMachine@5315b42e]" name="testStateTransition" class="org.killbill.automaton.TestStateMachine"/>
      </group> 
    </groups>
    <test name="Command line test" duration-ms="295" started-at="2014-06-25T00:53:18Z" finished-at="2014-06-25T00:53:18Z">
      <class name="org.killbill.automaton.TestStateMachine">
        <test-method status="PASS" signature="testLinkedStateMachines()[pri:0, instance:org.killbill.automaton.TestStateMachine@5315b42e]" name="testLinkedStateMachines" duration-ms="201" started-at="2014-06-24T17:53:18Z" finished-at="2014-06-24T17:53:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> 
        <test-method status="PASS" signature="testStateMachine()[pri:0, instance:org.killbill.automaton.TestStateMachine@5315b42e]" name="testStateMachine" duration-ms="27" started-at="2014-06-24T17:53:18Z" finished-at="2014-06-24T17:53:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> 
        <test-method status="PASS" signature="testStateTransition()[pri:0, instance:org.killbill.automaton.TestStateMachine@5315b42e]" name="testStateTransition" duration-ms="24" started-at="2014-06-24T17:53:18Z" finished-at="2014-06-24T17:53:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> 
      </class> 
      <class name="org.killbill.automaton.dot.TestDOTBuilder">
        <test-method status="FAIL" signature="testGenerator()[pri:0, instance:org.killbill.automaton.dot.TestDOTBuilder@6615435c]" name="testGenerator" duration-ms="30" started-at="2014-06-24T17:53:18Z" finished-at="2014-06-24T17:53:18Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [digraph Payment {
    splines=false;
    subgraph cluster_0 {
        label="Retry";
        node_0 [style=filled color=grey label=INIT];
        node_1 [style=filled color=grey label=SUCCESS];
        node_2 [style=filled color=grey label=FAILED];
        node_0 -> node_1 [label="Op|S"];
        node_0 -> node_2 [label="Op|F"];
        node_2 -> node_2 [label="Op|F"];
    }
    subgraph cluster_1 {
        label="Transaction";
        subgraph cluster_2 {
            label="Authorize";
            node_3 [style=filled color=grey label=INIT];
            node_4 [style=filled color=grey label=SUCCESS];
            node_5 [style=filled color=grey label=FAILED];
            node_6 [label=PENDING];
            node_3 -> node_4 [label="Op|S"];
            node_3 -> node_5 [label="Op|F"];
            node_3 -> node_6 [label="Op|P"];
            node_6 -> node_4 [label="Op|S"];
            node_6 -> node_5 [label="Op|F"];
        }
        subgraph cluster_3 {
            label="Capture";
            node_7 [style=filled color=grey label=INIT];
            node_8 [style=filled color=grey label=SUCCESS];
            node_9 [style=filled color=grey label=FAILED];
            node_7 -> node_8 [label="Op|S"];
            node_7 -> node_9 [label="Op|F"];
        }
        subgraph cluster_4 {
            label="Purchase";
            node_10 [style=filled color=grey label=INIT];
            node_11 [style=filled color=grey label=SUCCESS];
            node_12 [style=filled color=grey label=FAILED];
            node_10 -> node_11 [label="Op|S"];
            node_10 -> node_12 [label="Op|F"];
        }
        subgraph cluster_5 {
            label="Void";
            node_13 [style=filled color=grey label=INIT];
            node_14 [style=filled color=grey label=SUCCESS];
            node_15 [style=filled color=grey label=FAILED];
            node_13 -> node_14 [label="Op|S"];
            node_13 -> node_15 [label="Op|F"];
        }
        subgraph cluster_6 {
            label="Refund";
            node_16 [style=filled color=grey label=INIT];
            node_17 [style=filled color=grey label=SUCCESS];
            node_18 [style=filled color=grey label=FAILED];
            node_16 -> node_17 [label="Op|S"];
            node_16 -> node_18 [label="Op|F"];
        }
        node_4 -> node_7 [style=dotted label=CAPTURE_AMOUNT_CHECK];
        node_4 -> node_13 [style=dotted];
        node_8 -> node_13 [style=dotted];
        node_8 -> node_16 [style=dotted label=REFUND_AMOUNT_CHECK];
        node_11 -> node_16 [style=dotted label=REFUND_AMOUNT_CHECK];
    }
    subgraph cluster_7 {
        label="DirectPayment";
        node_19 [style=filled color=grey label=INIT];
        node_20 [style=filled color=grey label=OPEN];
        node_21 [style=filled color=grey label=CLOSED];
        node_19 -> node_20;
        node_20 -> node_21;
        node_19 -> node_3 [style=dotted color=blue];
        node_19 -> node_10 [style=dotted color=blue];
        node_20 -> node_4 [style=dotted color=green];
        node_20 -> node_8 [style=dotted color=green];
        node_21 -> node_17 [style=dotted color=green];
        node_21 -> node_14 [style=dotted color=green];
    }
}
] but found [digraph Payment {
    splines=false;
    subgraph cluster_0 {
        label="Retry";
        node_0 [color=grey style=filled label=INIT];
        node_1 [color=grey style=filled label=SUCCESS];
        node_2 [color=grey style=filled label=FAILED];
        node_0 -> node_1 [label="Op|S"];
        node_0 -> node_2 [label="Op|F"];
        node_2 -> node_2 [label="Op|F"];
    }
    subgraph cluster_1 {
        label="Transaction";
        subgraph cluster_2 {
            label="Authorize";
            node_3 [color=grey style=filled label=INIT];
            node_4 [color=grey style=filled label=SUCCESS];
            node_5 [color=grey style=filled label=FAILED];
            node_6 [label=PENDING];
            node_3 -> node_4 [label="Op|S"];
            node_3 -> node_5 [label="Op|F"];
            node_3 -> node_6 [label="Op|P"];
            node_6 -> node_4 [label="Op|S"];
            node_6 -> node_5 [label="Op|F"];
        }
        subgraph cluster_3 {
            label="Capture";
            node_7 [color=grey style=filled label=INIT];
            node_8 [color=grey style=filled label=SUCCESS];
            node_9 [color=grey style=filled label=FAILED];
            node_7 -> node_8 [label="Op|S"];
            node_7 -> node_9 [label="Op|F"];
        }
        subgraph cluster_4 {
            label="Purchase";
            node_10 [color=grey style=filled label=INIT];
            node_11 [color=grey style=filled label=SUCCESS];
            node_12 [color=grey style=filled label=FAILED];
            node_10 -> node_11 [label="Op|S"];
            node_10 -> node_12 [label="Op|F"];
        }
        subgraph cluster_5 {
            label="Void";
            node_13 [color=grey style=filled label=INIT];
            node_14 [color=grey style=filled label=SUCCESS];
            node_15 [color=grey style=filled label=FAILED];
            node_13 -> node_14 [label="Op|S"];
            node_13 -> node_15 [label="Op|F"];
        }
        subgraph cluster_6 {
            label="Refund";
            node_16 [color=grey style=filled label=INIT];
            node_17 [color=grey style=filled label=SUCCESS];
            node_18 [color=grey style=filled label=FAILED];
            node_16 -> node_17 [label="Op|S"];
            node_16 -> node_18 [label="Op|F"];
        }
        node_4 -> node_7 [style=dotted label=CAPTURE_AMOUNT_CHECK];
        node_4 -> node_13 [style=dotted];
        node_8 -> node_13 [style=dotted];
        node_8 -> node_16 [style=dotted label=REFUND_AMOUNT_CHECK];
        node_11 -> node_16 [style=dotted label=REFUND_AMOUNT_CHECK];
    }
    subgraph cluster_7 {
        label="DirectPayment";
        node_19 [color=grey style=filled label=INIT];
        node_20 [color=grey style=filled label=OPEN];
        node_21 [color=grey style=filled label=CLOSED];
        node_19 -> node_20;
        node_20 -> node_21;
        node_19 -> node_3 [style=dotted color=blue];
        node_19 -> node_10 [style=dotted color=blue];
        node_20 -> node_4 [style=dotted color=green];
        node_20 -> node_8 [style=dotted color=green];
        node_21 -> node_17 [style=dotted color=green];
        node_21 -> node_14 [style=dotted color=green];
    }
}
]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [digraph Payment {
    splines=false;
    subgraph cluster_0 {
        label="Retry";
        node_0 [style=filled color=grey label=INIT];
        node_1 [style=filled color=grey label=SUCCESS];
        node_2 [style=filled color=grey label=FAILED];
        node_0 -> node_1 [label="Op|S"];
        node_0 -> node_2 [label="Op|F"];
        node_2 -> node_2 [label="Op|F"];
    }
    subgraph cluster_1 {
        label="Transaction";
        subgraph cluster_2 {
            label="Authorize";
            node_3 [style=filled color=grey label=INIT];
            node_4 [style=filled color=grey label=SUCCESS];
            node_5 [style=filled color=grey label=FAILED];
            node_6 [label=PENDING];
            node_3 -> node_4 [label="Op|S"];
            node_3 -> node_5 [label="Op|F"];
            node_3 -> node_6 [label="Op|P"];
            node_6 -> node_4 [label="Op|S"];
            node_6 -> node_5 [label="Op|F"];
        }
        subgraph cluster_3 {
            label="Capture";
            node_7 [style=filled color=grey label=INIT];
            node_8 [style=filled color=grey label=SUCCESS];
            node_9 [style=filled color=grey label=FAILED];
            node_7 -> node_8 [label="Op|S"];
            node_7 -> node_9 [label="Op|F"];
        }
        subgraph cluster_4 {
            label="Purchase";
            node_10 [style=filled color=grey label=INIT];
            node_11 [style=filled color=grey label=SUCCESS];
            node_12 [style=filled color=grey label=FAILED];
            node_10 -> node_11 [label="Op|S"];
            node_10 -> node_12 [label="Op|F"];
        }
        subgraph cluster_5 {
            label="Void";
            node_13 [style=filled color=grey label=INIT];
            node_14 [style=filled color=grey label=SUCCESS];
            node_15 [style=filled color=grey label=FAILED];
            node_13 -> node_14 [label="Op|S"];
            node_13 -> node_15 [label="Op|F"];
        }
        subgraph cluster_6 {
            label="Refund";
            node_16 [style=filled color=grey label=INIT];
            node_17 [style=filled color=grey label=SUCCESS];
            node_18 [style=filled color=grey label=FAILED];
            node_16 -> node_17 [label="Op|S"];
            node_16 -> node_18 [label="Op|F"];
        }
        node_4 -> node_7 [style=dotted label=CAPTURE_AMOUNT_CHECK];
        node_4 -> node_13 [style=dotted];
        node_8 -> node_13 [style=dotted];
        node_8 -> node_16 [style=dotted label=REFUND_AMOUNT_CHECK];
        node_11 -> node_16 [style=dotted label=REFUND_AMOUNT_CHECK];
    }
    subgraph cluster_7 {
        label="DirectPayment";
        node_19 [style=filled color=grey label=INIT];
        node_20 [style=filled color=grey label=OPEN];
        node_21 [style=filled color=grey label=CLOSED];
        node_19 -> node_20;
        node_20 -> node_21;
        node_19 -> node_3 [style=dotted color=blue];
        node_19 -> node_10 [style=dotted color=blue];
        node_20 -> node_4 [style=dotted color=green];
        node_20 -> node_8 [style=dotted color=green];
        node_21 -> node_17 [style=dotted color=green];
        node_21 -> node_14 [style=dotted color=green];
    }
}
] but found [digraph Payment {
    splines=false;
    subgraph cluster_0 {
        label="Retry";
        node_0 [color=grey style=filled label=INIT];
        node_1 [color=grey style=filled label=SUCCESS];
        node_2 [color=grey style=filled label=FAILED];
        node_0 -> node_1 [label="Op|S"];
        node_0 -> node_2 [label="Op|F"];
        node_2 -> node_2 [label="Op|F"];
    }
    subgraph cluster_1 {
        label="Transaction";
        subgraph cluster_2 {
            label="Authorize";
            node_3 [color=grey style=filled label=INIT];
            node_4 [color=grey style=filled label=SUCCESS];
            node_5 [color=grey style=filled label=FAILED];
            node_6 [label=PENDING];
            node_3 -> node_4 [label="Op|S"];
            node_3 -> node_5 [label="Op|F"];
            node_3 -> node_6 [label="Op|P"];
            node_6 -> node_4 [label="Op|S"];
            node_6 -> node_5 [label="Op|F"];
        }
        subgraph cluster_3 {
            label="Capture";
            node_7 [color=grey style=filled label=INIT];
            node_8 [color=grey style=filled label=SUCCESS];
            node_9 [color=grey style=filled label=FAILED];
            node_7 -> node_8 [label="Op|S"];
            node_7 -> node_9 [label="Op|F"];
        }
        subgraph cluster_4 {
            label="Purchase";
            node_10 [color=grey style=filled label=INIT];
            node_11 [color=grey style=filled label=SUCCESS];
            node_12 [color=grey style=filled label=FAILED];
            node_10 -> node_11 [label="Op|S"];
            node_10 -> node_12 [label="Op|F"];
        }
        subgraph cluster_5 {
            label="Void";
            node_13 [color=grey style=filled label=INIT];
            node_14 [color=grey style=filled label=SUCCESS];
            node_15 [color=grey style=filled label=FAILED];
            node_13 -> node_14 [label="Op|S"];
            node_13 -> node_15 [label="Op|F"];
        }
        subgraph cluster_6 {
            label="Refund";
            node_16 [color=grey style=filled label=INIT];
            node_17 [color=grey style=filled label=SUCCESS];
            node_18 [color=grey style=filled label=FAILED];
            node_16 -> node_17 [label="Op|S"];
            node_16 -> node_18 [label="Op|F"];
        }
        node_4 -> node_7 [style=dotted label=CAPTURE_AMOUNT_CHECK];
        node_4 -> node_13 [style=dotted];
        node_8 -> node_13 [style=dotted];
        node_8 -> node_16 [style=dotted label=REFUND_AMOUNT_CHECK];
        node_11 -> node_16 [style=dotted label=REFUND_AMOUNT_CHECK];
    }
    subgraph cluster_7 {
        label="DirectPayment";
        node_19 [color=grey style=filled label=INIT];
        node_20 [color=grey style=filled label=OPEN];
        node_21 [color=grey style=filled label=CLOSED];
        node_19 -> node_20;
        node_20 -> node_21;
        node_19 -> node_3 [style=dotted color=blue];
        node_19 -> node_10 [style=dotted color=blue];
        node_20 -> node_4 [style=dotted color=green];
        node_20 -> node_8 [style=dotted color=green];
        node_21 -> node_17 [style=dotted color=green];
        node_21 -> node_14 [style=dotted color=green];
    }
}
]
    at org.testng.Assert.fail(Assert.java:94)
    at org.testng.Assert.failNotEquals(Assert.java:494)
    at org.testng.Assert.assertEquals(Assert.java:123)
    at org.testng.Assert.assertEquals(Assert.java:176)
    at org.testng.Assert.assertEquals(Assert.java:186)
    at org.killbill.automaton.dot.TestDOTBuilder.testGenerator(TestDOTBuilder.java:115)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
    at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
    at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
    at org.testng.TestRunner.privateRun(TestRunner.java:767)
    at org.testng.TestRunner.run(TestRunner.java:617)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
    at org.testng.SuiteRunner.run(SuiteRunner.java:254)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
    at org.testng.TestNG.run(TestNG.java:1057)
    at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
    at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:189)
    at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:105)
    at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:117)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:158)
    at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:86)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
]]>
            </full-stacktrace>
          </exception> 
          <reporter-output>
          </reporter-output>
        </test-method> 
      </class> 
    </test> 
  </suite> 
</testng-results>
GM16799:surefire-reports kpostlewaite$

**Comment by pierre** [comment]
Fixed by https://github.com/killbill/killbill-commons/commit/3979ffe222e2618dfa76f301c32ccea1403cbf25.
