### ISSUE TITLE
Reaper should not reap entries when there is only one node

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill-commons#47]
In scenario where there is only one node, reaping late notifications with the same `Creator` name should lead to no-op. This is an edge case, but can happen on testing environment.

**Comment by kuguobing** [comment]
org.killbill.queue.DBBackedQueue:: reapEntries()  

} else if (entryCreatedByThisNodeAndNeverProcessed) {
        lateEntries.**addAll**(entriesLeftBehind);   ==> shoud be :  **lateEntries.add(entryLeftBehind)**
 } else {

**Comment by pierre** [comment]
@kuguobing Thanks for the report, fixed in https://github.com/killbill/killbill-commons/pull/163.

**Comment by kuguobing** [comment]
> @kuguobing Thanks for the report, fixed in #163.

You're very welcome. 
killbill db queue is very nice for a lot of scenarios，thank you!

**Comment by kuguobing** [comment]
> @kuguobing Thanks for the report, fixed in #163.



> @kuguobing Thanks for the report, fixed in #163.
@pierre 
You're very welcome.
killbill db queue is very nice for a lot of scenarios，thank you!

**Comment by kuguobing** [comment]
> @kuguobing Thanks for the report, fixed in #163.
@pierre 
You're very welcome.
killbill db queue is very nice for a lot of scenarios，thank you!
