### ISSUE TITLE
can find ColonStatementLexer

### ISSUE THREAD

**Issue by liwenzlw** [killbill/killbill-commons#82]
It can't find ColonStatementLexer
![image](https://user-images.githubusercontent.com/18142468/88268447-117a9c00-cd05-11ea-9afd-96b2f67dbc21.png)

if i import jdbi , the argument incompatible
<dependency>
            <groupId>org.jdbi</groupId>
            <artifactId>jdbi</artifactId>
            <version>2.78</version>
        </dependency>

![image](https://user-images.githubusercontent.com/18142468/88268636-57376480-cd05-11ea-9fd5-d9093e97f304.png)

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [our communication guidelines](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
