### ISSUE TITLE
single node consumer can not comsume message

### ISSUE THREAD

**Issue by orangeyts** [killbill/killbill-commons#92]
we has single node consumer, when this node is down or deploying,
then producer post message , message can be move to history table ,but message handler not  invoker，

I check sourcecode, found no subscribers can found , 

so  I   register first ,then start queue, but found "Attempting to register handler " + handlerInstance + " in a non initialized bus"

any help?

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [our communication guidelines](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
